name: Pack to NuGet

on:
  workflow_dispatch:
    inputs:
      Upload_to_NuGet:
        description: 'Upload to NuGet'
        default: true
        type: boolean
      Ursa:
        description: 'Pack Ursa'
        default: true
        type: boolean
      Ursa_Themes_Semi:
        description: 'Pack Ursa.Themes.Semi'
        default: true
        type: boolean
      PrismExtension:
        description: 'Pack Prism Extension'
        default: false
        type: boolean
      ReactiveUIExtension:
        description: 'Pack ReactiveUI Extension'
        default: false
        type: boolean
  workflow_call:
    inputs:
      Upload_to_NuGet:
        type: boolean
        default: false
      Ursa:
        default: true
        type: boolean
      Ursa_Themes_Semi:
        default: true
        type: boolean
      PrismExtension:
        default: false
        type: boolean
      ReactiveUIExtension:
        default: false
        type: boolean

jobs:
  Pack_to_NuGet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Pack Ursa
        if: ${{ inputs.Ursa }}
        run: dotnet pack src/Ursa -o nugets

      - name: Pack Ursa.Themes.Semi
        if: ${{ inputs.Ursa_Themes_Semi }}
        run: dotnet pack src/Ursa.Themes.Semi -o nugets

      - name: Pack Prism Extension
        if: ${{ inputs.PrismExtension }}
        run: dotnet pack src/Ursa.PrismExtension -o nugets

      - name: Pack ReactiveUI Extension
        if: ${{ inputs.ReactiveUIExtension }}
        run: dotnet pack src/Ursa.ReactiveUIExtension -o nugets

      - name: Upload to NuGet
        if: ${{ inputs.Upload_to_NuGet }}
        run: dotnet nuget push "nugets/*.nupkg" --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nugets
          path: nugets
        if: always()