name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Ursa Unit Test
        run: dotnet test tests/Test.Ursa
      - name: Ursa Headless Test
        run: dotnet test tests/HeadlessTest.Ursa

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Ursa Unit Test
        run: dotnet test tests/Test.Ursa
      - name: Ursa Headless Test
        run: dotnet test tests/HeadlessTest.Ursa
